steps:
- name: 'cloud-builders/docker'
  args: ['build', '-t', 'whitef-data-b8eff/scenery:$SHORT_SHA', '.']

- name: 'cloud-builders/docker'
  args: ['push', 'gcr.io/whitef-data-b8eff/scenery:$SHORT_SHA']

- name: 'google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'docker-container',
         '--image', 'gcr.io/whitef-data-b8eff/scenery:$SHORT_SHA',
         '--region', 'europe-west1',
         '--platform', 'managed',
         '--allow-unauthenticated']

logsBucket: 'gs://docker-containerpdt'

timeout: '1200s'

images:
- 'whitef-data-b8eff/scenery:$SHORT_SHA'

serviceAccount: 'firebase-adminsdk-5rbg4@whitef-data-b8eff.iam.gserviceaccount.com'
